# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Matik"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://example.com/"
tags = []
features = []
<<<<<<< HEAD
min_version = "0.29"

[author]
  name = "Jotosman"
=======
min_version = "0.27.1"

[author]
  name = ""
>>>>>>> acadab526481cab74ad96dc14d27df6d705b4100
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
